"use client";
/* eslint-disable @next/next/no-img-element -- signed reviewer previews are short-lived URLs */

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { getBrowserSupabase } from "@/lib/supabase/client";
import { backendEndpoint } from "@/lib/external-services";
import { AuthGuard } from "@/components/protected-action";

type QueueItem = { id:string; submission_kind:"promise"|"proof"; title:string; promise_text:string; source_url:string|null; proof_path:string|null; proof_url:string|null; proof_mime_type:string|null; state:string; district:string|null; category:string; accountable_office:string|null; ai_warnings:string[]; created_at:string; target_commitment?:{id:string;slug:string;title:string;status:string;progress:number}|null };

export default function ReviewPage() {
  const router=useRouter();
  const [items,setItems]=useState<QueueItem[]>([]);
  const [notes,setNotes]=useState<Record<string,string>>({});
  const [progress,setProgress]=useState<Record<string,number>>({});
  const [complete,setComplete]=useState<Record<string,boolean>>({});
  const [loading,setLoading]=useState(true);

  const load=useCallback(async()=>{const supabase=getBrowserSupabase();const{data:{session}}=await supabase?.auth.getSession()??{data:{session:null}};if(!session){router.replace("/login?next=/review");return;}const promise=new URLSearchParams(window.location.search).get("promise");const endpoint=backendEndpoint(`/v1/review/submissions${promise?`?promise=${encodeURIComponent(promise)}`:""}`);if(!endpoint){toast.error("The review queue is temporarily unavailable.");setLoading(false);return;}const response=await fetch(endpoint,{headers:{authorization:`Bearer ${session.access_token}`}});const body=await response.json();if(response.ok){const queued=body.submissions??[];setItems(queued);setProgress(Object.fromEntries(queued.filter((item:QueueItem)=>item.submission_kind==="proof").map((item:QueueItem)=>[item.id,item.target_commitment?.progress??0])));}else toast.error(body.error);setLoading(false);},[router]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);

  const decide=async(item:QueueItem,decision:"accepted"|"rejected"|"needs_info")=>{const supabase=getBrowserSupabase();const{data:{session}}=await supabase?.auth.getSession()??{data:{session:null}};if(!session)return;const endpoint=backendEndpoint("/v1/review/submissions");if(!endpoint)return toast.error("The review action is temporarily unavailable.");const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify({submissionId:item.id,decision,note:notes[item.id]??"Reviewed against the original source.",progressAfter:item.submission_kind==="proof"?progress[item.id]:undefined,markCompleted:item.submission_kind==="proof"?complete[item.id]??false:false})});const body=await response.json();if(!response.ok)return toast.error(body.error);toast.success(item.submission_kind==="proof"&&decision==="accepted"?"Proof accepted and the public record was updated.":`Submission ${decision.replace("_"," ")}.`);setItems(old=>old.filter(entry=>entry.id!==item.id));};

  return <main className="site-shell route-shell"><SiteHeader/><AuthGuard roles={["reviewer","admin"]}><section className="review-page"><div className="review-head"><div><p className="eyebrow">HUMAN &amp; AUTHORITY REVIEW QUEUE</p><h1>Evidence moves<br/>the record.</h1></div><strong>{String(items.length).padStart(2,"0")} WAITING</strong></div>{loading&&<div className="record-empty">Loading review queue…</div>}{!loading&&!items.length&&<div className="record-empty"><h2>The review queue is clear.</h2><p>There are no public submissions waiting for a reviewer decision.</p></div>}<div className="review-list">{items.map(item=><article key={item.id}><div className="card-topline"><span>{item.submission_kind==="proof"?"PROGRESS PROOF":"NEW PROMISE"}</span><span>{item.state} · {item.district||"District not stated"}</span><span>{new Date(item.created_at).toLocaleDateString("en-IN")}</span></div>{item.target_commitment&&<div className="review-target"><span>UPDATES RECORD</span><a href={`/promises/${item.target_commitment.slug}`}>{item.target_commitment.title} ↗</a></div>}<h2>{item.title}</h2><p>{item.promise_text}</p>{item.ai_warnings?.length>0&&<div className="warning-box">{item.ai_warnings.map(warning=><p key={warning}>! {warning}</p>)}</div>}{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">Inspect original source ↗</a>}{item.proof_path&&item.proof_url&&item.proof_mime_type?.startsWith("image/")&&<img className="review-image-preview" src={item.proof_url} alt={`Private evidence preview for ${item.title}`} />}{item.proof_path&&<a className="review-uploaded" href={item.proof_url??"#"} target="_blank" rel="noreferrer">{item.proof_url?`Inspect private uploaded ${item.proof_mime_type?.startsWith("image/")?"image":"document"} ↗`:"Private upload unavailable"}</a>}{item.submission_kind==="proof"&&<div className="authority-decision"><label>Verified progress after this proof<input type="number" min="0" max="100" value={progress[item.id]??0} onChange={event=>setProgress(old=>({...old,[item.id]:Number(event.target.value)}))}/></label><label className="choice"><input type="checkbox" checked={complete[item.id]??false} onChange={event=>{setComplete(old=>({...old,[item.id]:event.target.checked}));if(event.target.checked)setProgress(old=>({...old,[item.id]:100}));}}/> Mark promise completed and close tracking</label></div>}<label>Public decision note<textarea rows={3} value={notes[item.id]??""} onChange={event=>setNotes(old=>({...old,[item.id]:event.target.value}))}/></label><div className="review-actions"><button onClick={()=>decide(item,"rejected")}>Reject</button><button onClick={()=>decide(item,"needs_info")}>Needs info</button><button className="accept" onClick={()=>decide(item,"accepted")}>{item.submission_kind==="proof"?"Accept proof & update":"Accept & publish"}</button></div></article>)}</div></section></AuthGuard><SiteFooter /></main>;
}
