"use client";

import { useEffect, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { getBrowserSupabase } from "@/lib/supabase/client";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { backendEndpoint } from "@/lib/external-services";

type Log={id:string;title:string;state:string;status:string;created_at:string;review_note:string|null};
export default function MyLogsPage(){const [logs,setLogs]=useState<Log[]>([]);const [loading,setLoading]=useState(isSupabaseConfigured);useEffect(()=>{if(!isSupabaseConfigured)return;const timer=window.setTimeout(()=>{const supabase=getBrowserSupabase();if(!supabase)return;void(async()=>{let {data:{session}}=await supabase.auth.getSession();if(!session){const signed=await supabase.auth.signInAnonymously();session=signed.data.session;}if(session){const endpoint=backendEndpoint("/v1/me/submissions");if(endpoint){const response=await fetch(endpoint,{headers:{authorization:`Bearer ${session.access_token}`}});const body=await response.json();if(response.ok)setLogs((body.submissions as Log[])??[]);}}setLoading(false);})();},0);return()=>window.clearTimeout(timer);},[]);
return <main className="site-shell route-shell"><SiteHeader/><section className="logs-page"><div><p className="eyebrow">YOUR PRIVATE RECEIPTS</p><h1>My logs.</h1><p>This page uses an anonymous secure session on this device. Your public identity is not required.</p></div><div className="logs-list">{loading&&<div className="record-empty">Loading secure receipts…</div>}{!loading&&!isSupabaseConfigured&&<div className="record-empty"><h2>Submission storage is not connected in this preview.</h2><p>The production schema and privacy rules are included; connecting the Supabase environment enables device private logs.</p><a href="/submit">Try the assisted form →</a></div>}{!loading&&isSupabaseConfigured&&!logs.length&&<div className="record-empty"><h2>No submissions from this device.</h2><p>When you send a promise or proof, its private receipt and review decision will appear here.</p><a href="/submit">Record a promise →</a></div>}{logs.map(log=><article key={log.id}><div><span>{new Date(log.created_at).toLocaleDateString("en-IN")}</span><span className={`log-status ${log.status}`}>{log.status.replaceAll("_"," ")}</span></div><h2>{log.title}</h2><p>{log.state} · receipt {log.id.slice(0,8)}</p>{log.review_note&&<blockquote>{log.review_note}</blockquote>}</article>)}</div></section></main>}
