import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { evidenceHref, isImageEvidence } from "@/lib/evidence-links";
import { getCommitmentBySlug } from "@/lib/repository";
import { publicStatusLabel } from "@/lib/status";

const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):"Not stated";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const item=await getCommitmentBySlug(slug);return{title:item?`${item.title} | Vaada`:"Record not found | Vaada",description:item?.detail,openGraph:item?{title:item.title,description:item.detail,images:[]}:undefined,twitter:item?{card:"summary",title:item.title,description:item.detail,images:[]}:undefined};}

export default async function PromiseDetailPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const item=await getCommitmentBySlug(slug);if(!item)notFound();
  const receipts=item.evidence.filter(entry=>entry.kind==="receipt");const proofs=item.evidence.filter(entry=>entry.kind==="proof");
  return <main className="site-shell route-shell"><SiteHeader/><section className="record-hero"><div className="record-kicker"><a href="/promises">← PUBLIC REGISTER</a><span>{item.state} · {item.district}</span><span className={`status ${item.status==="broken"?"late":item.status==="fulfilled"?"done":"progress"}`}><i/>{publicStatusLabel(item.status)}</span></div><p className="prototype-label">PUBLIC PROMISE RECORD</p><h1>{item.title}</h1><p>{item.detail}</p><div className="record-progress"><div><span>VERIFIED PROGRESS</span><strong>{item.progress}%</strong></div><div className="progress-track"><span style={{width:`${item.progress}%`}}/></div><small>Last reviewed {date(item.lastReviewedAt)}</small></div></section>
    <section className="record-body"><aside><p className="eyebrow">THE CLAIM</p><dl className="record-facts"><div><dt>Promised</dt><dd>{date(item.promisedOn)}</dd></div><div><dt>Stated deadline</dt><dd>{date(item.deadline)}{item.deadlineLabel&&<small>{item.deadlineLabel}</small>}</dd></div><div><dt>Responsible office</dt><dd>{item.accountableOffice}</dd></div>{item.accountablePerson&&<div><dt>Named person</dt><dd>{item.accountablePerson}</dd></div>}<div><dt>People affected</dt><dd>{item.beneficiaries}</dd></div><div><dt>Sector</dt><dd>{item.category}</dd></div></dl></aside>
      <div className="record-content"><section><p className="eyebrow">ORIGINAL PROMISE SOURCE</p><h2>What put this promise on record</h2>{receipts.length?<div className="evidence-list">{receipts.map(evidence=><article key={evidence.id}><div><span>RECEIPT</span><span className={`verdict ${evidence.verdict}`}>{evidence.verdict}</span></div><h3>{evidence.title}</h3>{evidence.quote&&<blockquote>“{evidence.quote}”</blockquote>}<p>{date(evidence.documentDate)} · reviewed {date(evidence.reviewedAt??null)}</p><a href={evidenceHref(evidence)} target="_blank" rel="noreferrer">View original source ↗</a></article>)}</div>:<div className="record-empty">The founding source is awaiting publication review.</div>}</section>
        <section id="completion-proof"><p className="eyebrow">COMPLETION &amp; PROGRESS PROOF</p><h2>Proof submitted by the public or authority</h2>{proofs.length?<div className="evidence-list completion-evidence">{proofs.map(evidence=><article key={evidence.id}><div><span>PROOF</span><span className={`verdict ${evidence.verdict}`}>{evidence.verdict}</span></div><h3>{evidence.title}</h3>{isImageEvidence(evidence)&&<Image className="evidence-preview" src={evidenceHref(evidence)} alt={`Verified proof for ${item.title}`} width={900} height={620} unoptimized/>}{evidence.quote&&<blockquote>“{evidence.quote}”</blockquote>}<p>{date(evidence.documentDate)} · reviewed {date(evidence.reviewedAt??null)}</p><a href={evidenceHref(evidence)} target="_blank" rel="noreferrer">{evidence.storagePath?"View uploaded proof":"Inspect completion proof"} ↗</a></article>)}</div>:<div className="record-empty">No completion proof has been accepted yet. Anyone can submit a link, image, PDF or signed letter for review.</div>}</section>
        <section><p className="eyebrow">PUBLIC HISTORY</p><h2>Record timeline</h2>{item.timeline.length?<ol className="timeline">{item.timeline.map(event=><li key={event.id}><time>{date(event.date)}</time><div><h3>{event.title}</h3><p>{event.detail}</p></div></li>)}</ol>:<div className="record-empty">No public timeline events yet.</div>}</section>
        <section className="record-actions"><h2>Know something this record is missing?</h2><p>Citizens and public authorities can upload a source, completion image, signed letter or public link. AI drafts the evidence fields, but a human reviewer decides whether progress changes.</p><div className="record-action-buttons"><a className="button button-primary" href={`/submit?promise=${item.slug}&mode=proof`}>Upload public proof <span>↗</span></a><a className="button authority-button" href={`/review?promise=${item.slug}`}>Authority verify or close <span>✓</span></a></div></section></div></section><SiteFooter/></main>;
}
