import type { Commitment } from "./types";

export const commitments: Commitment[] = [
  {
    id: "cmt-rajasthan-schools",
    slug: "rajasthan-50-digital-classrooms",
    title: "Upgrade 50 government schools with digital classrooms",
    detail: "The School Education Department announced that 50 government schools in Jaipur district would receive digital classroom equipment, teacher training and reliable connectivity by the end of the 2026/27 financial year.",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    district: "Jaipur",
    districtSlug: "jaipur",
    category: "Education",
    status: "in_progress",
    promisedOn: "2025-02-14",
    deadline: "2027-03-31",
    deadlineLabel: "By the end of FY 2026/27",
    progress: 64,
    beneficiaries: "50 schools · approximately 18,400 students",
    accountableOffice: "Department of School Education",
    lastReviewedAt: "2026-08-15",
    evidence: [
      { id: "rec-1", kind: "receipt", title: "Department programme announcement", sourceKind: "document_link", sourceUrl: "https://education.rajasthan.gov.in/", quote: "Digital classroom facilities will be introduced in fifty government schools.", verdict: "verified", documentDate: "2025-02-14", reviewedAt: "2026-07-02" },
      { id: "proof-1", kind: "proof", title: "Installation progress report", sourceKind: "media", sourceUrl: "https://education.rajasthan.gov.in/", direction: "supports", verdict: "verified", documentDate: "2026-08-09", reviewedAt: "2026-08-15" },
    ],
    timeline: [
      { id: "tl-1", date: "2025-02-14", title: "Promise recorded", detail: "The programme announcement named 50 Jaipur district schools.", type: "promise" },
      { id: "tl-2", date: "2026-08-15", title: "Progress updated to 64%", detail: "Accepted installation records covered 32 of the 50 schools.", type: "evidence" },
    ],
  },
  {
    id: "cmt-up-water",
    slug: "varanasi-18-villages-piped-water",
    title: "Complete piped drinking water coverage across 18 villages",
    detail: "The district water mission stated that household piped water connections would cover eighteen listed villages in Varanasi district before June 2026.",
    state: "Uttar Pradesh",
    stateSlug: "uttar-pradesh",
    district: "Varanasi",
    districtSlug: "varanasi",
    category: "Water",
    status: "broken",
    promisedOn: "2024-08-09",
    deadline: "2026-06-30",
    deadlineLabel: "By June 2026",
    progress: 38,
    beneficiaries: "18 villages · approximately 32,000 residents",
    accountableOffice: "District Water & Sanitation Mission",
    lastReviewedAt: "2026-08-18",
    evidence: [
      { id: "rec-2", kind: "receipt", title: "District mission announcement", sourceKind: "press_link", sourceUrl: "https://jjm.up.gov.in/", quote: "All eighteen villages are targeted for household tap coverage by June 2026.", verdict: "verified", documentDate: "2024-08-09", reviewedAt: "2026-07-05" },
      { id: "proof-2", kind: "proof", title: "Village level field update", sourceKind: "media", sourceUrl: "https://jjm.up.gov.in/", direction: "supports", verdict: "verified", documentDate: "2026-08-10", reviewedAt: "2026-08-18" },
    ],
    timeline: [
      { id: "tl-3", date: "2024-08-09", title: "Promise recorded", detail: "Eighteen villages were named in the public announcement.", type: "promise" },
      { id: "tl-4", date: "2026-07-01", title: "Stated deadline passed", detail: "No verified evidence supported complete coverage by the stated date.", type: "status" },
    ],
  },
  {
    id: "cmt-maharashtra-hospital",
    slug: "nashik-100-bed-maternal-wing",
    title: "Open a 100 bed public hospital wing for maternal care",
    detail: "The Public Health Department committed to commission a new maternal and newborn care wing with one hundred beds in Nashik.",
    state: "Maharashtra",
    stateSlug: "maharashtra",
    district: "Nashik",
    districtSlug: "nashik",
    category: "Health",
    status: "fulfilled",
    promisedOn: "2023-11-21",
    deadline: "2026-07-15",
    deadlineLabel: "Operational by 15 July 2026",
    progress: 100,
    beneficiaries: "100 beds · maternal and newborn care",
    accountableOffice: "Public Health Department",
    lastReviewedAt: "2026-07-22",
    evidence: [
      { id: "rec-3", kind: "receipt", title: "Signed hospital expansion order", sourceKind: "signed_document", sourceUrl: "https://arogya.maharashtra.gov.in/", quote: "A 100 bed maternal care wing shall be commissioned in Nashik.", verdict: "verified", documentDate: "2023-11-21", reviewedAt: "2026-06-10" },
      { id: "proof-3", kind: "proof", title: "Commissioning inspection", sourceKind: "signed_document", sourceUrl: "https://arogya.maharashtra.gov.in/", direction: "supports", verdict: "verified", documentDate: "2026-07-20", reviewedAt: "2026-07-22" },
    ],
    timeline: [
      { id: "tl-5", date: "2023-11-21", title: "Promise recorded", detail: "The signed order described the scope and stated date.", type: "promise" },
      { id: "tl-6", date: "2026-07-22", title: "Completion verified", detail: "The commissioning record and inspection media were accepted.", type: "status" },
    ],
  },
  {
    id: "cmt-bihar-road",
    slug: "gaya-rural-road-rehabilitation",
    title: "Rehabilitate 42 kilometres of flood damaged rural roads",
    detail: "The rural works department announced repair and resurfacing across a 42 km package connecting villages in Gaya district.",
    state: "Bihar", stateSlug: "bihar", district: "Gaya", districtSlug: "gaya", category: "Infrastructure", status: "promised",
    promisedOn: "2026-05-11", deadline: "2027-01-31", deadlineLabel: "Before 31 January 2027", progress: 12,
    beneficiaries: "14 village connections · 42 km", accountableOffice: "Rural Works Department", lastReviewedAt: "2026-08-11", evidence: [], timeline: [],
  },
  {
    id: "cmt-mp-clinic",
    slug: "bhopal-urban-health-clinics",
    title: "Open six neighbourhood primary health clinics",
    detail: "The municipal health programme announced six new clinics for underserved wards in Bhopal.",
    state: "Madhya Pradesh", stateSlug: "madhya-pradesh", district: "Bhopal", districtSlug: "bhopal", category: "Health", status: "in_progress",
    promisedOn: "2025-12-03", deadline: null, deadlineLabel: null, progress: 33, beneficiaries: "6 wards", accountableOffice: "Municipal Health Department", lastReviewedAt: "2026-08-01", evidence: [], timeline: [],
  },
  {
    id: "cmt-jharkhand-jobs",
    slug: "ranchi-apprenticeship-placements",
    title: "Create 5,000 paid apprenticeship placements for young people",
    detail: "A state skills programme announced a target of five thousand paid placements through industry partners.",
    state: "Jharkhand", stateSlug: "jharkhand", district: "Ranchi", districtSlug: "ranchi", category: "Jobs", status: "disputed",
    promisedOn: "2025-09-18", deadline: "2026-12-31", deadlineLabel: "During calendar year 2026", progress: 41, beneficiaries: "5,000 young people", accountableOffice: "Department of Labour, Employment, Training & Skill Development", lastReviewedAt: "2026-08-16", evidence: [], timeline: [],
  },
  {
    id: "cmt-karnataka-buses",
    slug: "bengaluru-1200-electric-buses",
    title: "Add 1,200 electric buses to Bengaluru’s public transport fleet",
    detail: "The state transport programme committed to adding 1,200 electric buses across twelve high demand Bengaluru corridors by the end of 2027.",
    state: "Karnataka", stateSlug: "karnataka", district: "Bengaluru", districtSlug: "bengaluru", category: "Transport", status: "in_progress",
    promisedOn: "2025-01-26", deadline: "2027-12-31", deadlineLabel: "By the end of 2027", progress: 46,
    beneficiaries: "1,200 buses · 12 major corridors", accountableOffice: "Department of Transport", lastReviewedAt: "2026-08-18", evidence: [], timeline: [],
  },
  {
    id: "cmt-odisha-irrigation",
    slug: "koraput-180-irrigation-systems",
    title: "Restore 180 minor irrigation systems across drought prone blocks",
    detail: "The Water Resources Department committed to restoring 180 minor irrigation systems serving drought prone farming blocks in Koraput district.",
    state: "Odisha", stateSlug: "odisha", district: "Koraput", districtSlug: "koraput", category: "Agriculture", status: "fulfilled",
    promisedOn: "2023-10-02", deadline: "2026-06-30", deadlineLabel: "Before 30 June 2026", progress: 100,
    beneficiaries: "180 systems · approximately 21,000 farmers", accountableOffice: "Department of Water Resources", lastReviewedAt: "2026-08-13",
    evidence: [
      { id: "rec-8", kind: "receipt", title: "Irrigation restoration programme order", sourceKind: "signed_document", sourceUrl: "https://dowr.odisha.gov.in/", quote: "Restoration work will cover one hundred and eighty minor irrigation systems in Koraput.", verdict: "verified", documentDate: "2023-10-02", reviewedAt: "2026-05-18" },
      { id: "proof-8", kind: "proof", title: "District completion and field inspection report", sourceKind: "signed_document", sourceUrl: "https://dowr.odisha.gov.in/", direction: "supports", verdict: "verified", documentDate: "2026-07-08", reviewedAt: "2026-08-13" },
    ],
    timeline: [
      { id: "tl-8a", date: "2023-10-02", title: "Promise recorded", detail: "The signed programme order listed 180 restoration sites.", type: "promise" },
      { id: "tl-8b", date: "2026-08-13", title: "Promise marked complete", detail: "The completion report and field inspection were accepted after human review.", type: "status" },
    ],
  },
  {
    id: "cmt-tamil-nadu-housing",
    slug: "chennai-8000-affordable-rental-homes",
    title: "Deliver 8,000 affordable rental homes for urban workers",
    detail: "The Urban Habitat Development Board announced an affordable rental housing programme for low income workers across Chennai.",
    state: "Tamil Nadu", stateSlug: "tamil-nadu", district: "Chennai", districtSlug: "chennai", category: "Housing", status: "promised",
    promisedOn: "2026-03-15", deadline: "2028-03-31", deadlineLabel: "By the end of FY 2027/28", progress: 18,
    beneficiaries: "8,000 homes · low income urban workers", accountableOffice: "Urban Habitat Development Board", lastReviewedAt: "2026-08-07", evidence: [], timeline: [],
  },
  {
    id: "cmt-bengaluru-pm-edrive-buses", slug: "bengaluru-4500-pm-edrive-electric-buses",
    title: "Provide approximately 4,500 electric buses to Bengaluru",
    detail: "The Ministry of Heavy Industries said approximately 4,500 electric buses would be provided to Bengaluru under the PM E DRIVE programme. A later parliamentary update said allocation and tendering had advanced, while deployment had not yet begun as of March 2026.",
    state: "Karnataka", stateSlug: "karnataka", district: "Bengaluru Urban", districtSlug: "bengaluru-urban", category: "Transport", status: "in_progress",
    promisedOn: "2025-05-22", deadline: null, deadlineLabel: "Deployment follows concession agreements and supply", progress: 20,
    beneficiaries: "Bengaluru public transport passengers", accountableOffice: "Ministry of Heavy Industries and Bengaluru transport undertakings", lastReviewedAt: "2026-03-17",
    evidence: [
      { id: "rec-blr-4500", kind: "receipt", title: "Major cities accelerate electric bus adoption under PM E DRIVE", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2130496", quote: "Approximately 4,500 electric buses will be provided to Bengaluru.", verdict: "verified", documentDate: "2025-05-22", reviewedAt: "2026-08-24" },
      { id: "proof-blr-tender", kind: "proof", title: "PM E DRIVE allocation and deployment status", sourceKind: "document_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2241269", direction: "supports", verdict: "verified", documentDate: "2026-03-17", reviewedAt: "2026-08-24" },
    ],
    timeline: [{ id: "tl-blr-1", date: "2025-05-22", title: "Promise recorded", detail: "PIB recorded the assurance for approximately 4,500 buses.", type: "promise" }, { id: "tl-blr-2", date: "2026-03-17", title: "Tender stage update", detail: "The official update reported allocations and tendering but no deployment yet under PM E DRIVE.", type: "evidence" }],
  },
  {
    id: "cmt-hyderabad-pm-edrive-buses", slug: "hyderabad-2000-pm-edrive-electric-buses",
    title: "Provide approximately 2,000 electric buses to Hyderabad", detail: "The Union government publicly stated that approximately 2,000 electric buses would be provided to Hyderabad under PM E DRIVE.",
    state: "Telangana", stateSlug: "telangana", district: "Hyderabad", districtSlug: "hyderabad", category: "Transport", status: "promised", promisedOn: "2025-05-22", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "Hyderabad public transport passengers", accountableOffice: "Ministry of Heavy Industries and Telangana transport undertakings", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-hyd-2000", kind: "receipt", title: "Major cities accelerate electric bus adoption under PM E DRIVE", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2130496", quote: "Approximately 2,000 electric buses will be provided to Hyderabad.", verdict: "verified", documentDate: "2025-05-22", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-ahmedabad-pm-edrive-buses", slug: "ahmedabad-1000-pm-edrive-electric-buses",
    title: "Provide approximately 1,000 electric buses to Ahmedabad", detail: "The Union government publicly stated that approximately 1,000 electric buses would be provided to Ahmedabad under PM E DRIVE.",
    state: "Gujarat", stateSlug: "gujarat", district: "Ahmedabad", districtSlug: "ahmedabad", category: "Transport", status: "promised", promisedOn: "2025-05-22", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "Ahmedabad public transport passengers", accountableOffice: "Ministry of Heavy Industries and Ahmedabad transport undertakings", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-amd-1000", kind: "receipt", title: "Major cities accelerate electric bus adoption under PM E DRIVE", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2130496", quote: "Approximately 1,000 electric buses will be provided to Ahmedabad.", verdict: "verified", documentDate: "2025-05-22", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-surat-pm-edrive-buses", slug: "surat-600-pm-edrive-electric-buses",
    title: "Provide approximately 600 electric buses to Surat", detail: "The Union government publicly stated that approximately 600 electric buses would be provided to Surat under PM E DRIVE.",
    state: "Gujarat", stateSlug: "gujarat", district: "Surat", districtSlug: "surat", category: "Transport", status: "promised", promisedOn: "2025-05-22", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "Surat public transport passengers", accountableOffice: "Ministry of Heavy Industries and Surat transport undertakings", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-surat-600", kind: "receipt", title: "Major cities accelerate electric bus adoption under PM E DRIVE", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2130496", quote: "Approximately 600 electric buses will be provided to Surat.", verdict: "verified", documentDate: "2025-05-22", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-delhi-pm-edrive-buses", slug: "delhi-2800-pm-edrive-electric-buses",
    title: "Provide approximately 2,800 electric buses to Delhi", detail: "The Union government publicly stated that approximately 2,800 electric buses would be provided to Delhi under PM E DRIVE.",
    state: "Delhi", stateSlug: "delhi", district: "New Delhi", districtSlug: "new-delhi", category: "Transport", status: "promised", promisedOn: "2025-05-22", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "Delhi public transport passengers", accountableOffice: "Ministry of Heavy Industries and Delhi transport undertakings", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-delhi-2800", kind: "receipt", title: "Major cities accelerate electric bus adoption under PM E DRIVE", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2130496", quote: "Approximately 2,800 electric buses will be provided to Delhi.", verdict: "verified", documentDate: "2025-05-22", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-varanasi-ropeway", slug: "varanasi-urban-ropeway-3-85-km",
    title: "Build a 3.85 kilometre urban ropeway in Varanasi", detail: "The Varanasi ropeway is listed under the national Parvatmala programme and was reported under construction in the Ministry of Road Transport and Highways' 2024 review.",
    state: "Uttar Pradesh", stateSlug: "uttar-pradesh", district: "Varanasi", districtSlug: "varanasi", category: "Transport", status: "in_progress", promisedOn: "2022-02-01", deadline: null, deadlineLabel: null, progress: 35,
    beneficiaries: "Urban commuters and visitors in Varanasi", accountableOffice: "Ministry of Road Transport and Highways", lastReviewedAt: "2025-12-31",
    evidence: [{ id: "rec-var-ropeway", kind: "receipt", title: "Parvatmala National Ropeways Development Programme", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2110398", quote: "Varanasi is listed among ropeway projects under construction.", verdict: "verified", documentDate: "2025-03-18", reviewedAt: "2026-08-24" }, { id: "proof-var-ropeway", kind: "proof", title: "Road ministry year end implementation update", sourceKind: "document_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2091508", direction: "supports", verdict: "verified", documentDate: "2024-12-31", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-prayagraj-ropeway", slug: "prayagraj-sangam-ropeway",
    title: "Develop a ropeway serving Sangam in Prayagraj", detail: "The Sangam ropeway in Prayagraj was listed as an awarded project under the Parvatmala programme.",
    state: "Uttar Pradesh", stateSlug: "uttar-pradesh", district: "Prayagraj", districtSlug: "prayagraj", category: "Transport", status: "in_progress", promisedOn: "2024-02-01", deadline: null, deadlineLabel: null, progress: 15,
    beneficiaries: "Residents, pilgrims and visitors", accountableOffice: "Ministry of Road Transport and Highways", lastReviewedAt: "2025-03-18",
    evidence: [{ id: "rec-prayagraj-ropeway", kind: "receipt", title: "Parvatmala National Ropeways Development Programme", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2110398", quote: "Sangam, Prayagraj is listed among awarded ropeway projects.", verdict: "verified", documentDate: "2025-03-18", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-ayodhya-jetties", slug: "ayodhya-two-steel-jetties",
    title: "Set up two steel jetties in Ayodhya", detail: "The Inland Waterways Development Council announced plans for two steel jetties in Ayodhya as part of inland water transport upgrades in Uttar Pradesh.",
    state: "Uttar Pradesh", stateSlug: "uttar-pradesh", district: "Ayodhya", districtSlug: "ayodhya", category: "Infrastructure", status: "promised", promisedOn: "2025-01-10", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "River transport users and local tourism", accountableOffice: "Inland Waterways Authority of India", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-ayodhya-jetties", kind: "receipt", title: "Inland waterways infrastructure upgrade announcement", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2091831", quote: "Two steel jetties are planned in Ayodhya.", verdict: "verified", documentDate: "2025-01-10", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-mathura-jetties", slug: "mathura-eight-floating-jetties",
    title: "Set up eight floating jetties in Mathura", detail: "The Inland Waterways Development Council announced plans for eight floating jetties in Mathura as part of Uttar Pradesh's inland water transport upgrades.",
    state: "Uttar Pradesh", stateSlug: "uttar-pradesh", district: "Mathura", districtSlug: "mathura", category: "Infrastructure", status: "promised", promisedOn: "2025-01-10", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "River transport users and local tourism", accountableOffice: "Inland Waterways Authority of India", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-mathura-jetties", kind: "receipt", title: "Inland waterways infrastructure upgrade announcement", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2091831", quote: "Eight floating jetties are planned in Mathura.", verdict: "verified", documentDate: "2025-01-10", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-ghazipur-ship-repair", slug: "ghazipur-ship-repair-facility",
    title: "Establish a ship repair facility in Ghazipur", detail: "The Inland Waterways Development Council announced a ship repair facility in Ghazipur intended to reduce vessel downtime.",
    state: "Uttar Pradesh", stateSlug: "uttar-pradesh", district: "Ghazipur", districtSlug: "ghazipur", category: "Infrastructure", status: "promised", promisedOn: "2025-01-10", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "Inland waterway operators and local workers", accountableOffice: "Inland Waterways Authority of India", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-ghazipur-repair", kind: "receipt", title: "Inland waterways infrastructure upgrade announcement", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2091831", quote: "A ship repair facility is to be established in Ghazipur.", verdict: "verified", documentDate: "2025-01-10", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-pune-metro-extension", slug: "pune-metro-phase-one-extension",
    title: "Complete the approved Pune Metro extension by February 2029", detail: "The approved Pune Metro expansion project carries a stated February 2029 completion target and an estimated cost of ₹2,954.53 crore.",
    state: "Maharashtra", stateSlug: "maharashtra", district: "Pune", districtSlug: "pune", category: "Transport", status: "in_progress", promisedOn: "2024-08-25", deadline: "2029-02-28", deadlineLabel: "By February 2029", progress: 10,
    beneficiaries: "Pune metropolitan commuters", accountableOffice: "Ministry of Housing and Urban Affairs and Maharashtra Metro Rail Corporation", lastReviewedAt: "2026-08-24",
    evidence: [{ id: "rec-pune-metro", kind: "receipt", title: "100 days of Modi 3.0 infrastructure approvals", sourceKind: "press_link", sourceUrl: "https://www.pib.gov.in/PressNoteDetails.aspx?ModuleId=3&NoteId=152155&lang=2&reg=3", quote: "The Pune project is set to be completed by February 2029.", verdict: "verified", documentDate: "2024-09-17", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-thane-navodaya", slug: "thane-new-navodaya-vidyalaya",
    title: "Establish a new Navodaya Vidyalaya in Thane district", detail: "The Government of India approved a new Navodaya Vidyalaya for an uncovered district in Thane as part of a wider December 2024 approval.",
    state: "Maharashtra", stateSlug: "maharashtra", district: "Thane", districtSlug: "thane", category: "Education", status: "promised", promisedOn: "2024-12-06", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "School age students in Thane district", accountableOffice: "Department of School Education and Literacy", lastReviewedAt: "2026-02-03",
    evidence: [{ id: "rec-thane-nv", kind: "receipt", title: "Government inputs for Maharashtra", sourceKind: "document_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2223801", quote: "A new Navodaya Vidyalaya was approved for Thane district.", verdict: "verified", documentDate: "2026-02-03", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-akola-kv", slug: "akola-new-kendriya-vidyalaya",
    title: "Establish a new Kendriya Vidyalaya in Akola district", detail: "The Government of India reported approval of a new Kendriya Vidyalaya in Akola district under the December 2024 national school expansion decision.",
    state: "Maharashtra", stateSlug: "maharashtra", district: "Akola", districtSlug: "akola", category: "Education", status: "promised", promisedOn: "2024-12-06", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "School age students in Akola district", accountableOffice: "Department of School Education and Literacy", lastReviewedAt: "2026-02-03",
    evidence: [{ id: "rec-akola-kv", kind: "receipt", title: "Government inputs for Maharashtra", sourceKind: "document_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2223801", quote: "A Kendriya Vidyalaya was approved in Akola district.", verdict: "verified", documentDate: "2026-02-03", reviewedAt: "2026-08-24" }], timeline: [],
  },
  {
    id: "cmt-ratnagiri-kv", slug: "ratnagiri-new-kendriya-vidyalaya",
    title: "Establish a new Kendriya Vidyalaya in Ratnagiri district", detail: "The Government of India reported approval of a new Kendriya Vidyalaya in Ratnagiri district under the December 2024 national school expansion decision.",
    state: "Maharashtra", stateSlug: "maharashtra", district: "Ratnagiri", districtSlug: "ratnagiri", category: "Education", status: "promised", promisedOn: "2024-12-06", deadline: null, deadlineLabel: null, progress: 0,
    beneficiaries: "School age students in Ratnagiri district", accountableOffice: "Department of School Education and Literacy", lastReviewedAt: "2026-02-03",
    evidence: [{ id: "rec-ratnagiri-kv", kind: "receipt", title: "Government inputs for Maharashtra", sourceKind: "document_link", sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2223801", quote: "A Kendriya Vidyalaya was approved in Ratnagiri district.", verdict: "verified", documentDate: "2026-02-03", reviewedAt: "2026-08-24" }], timeline: [],
  },
];

export const states = Array.from(new Set(commitments.map((item) => item.state))).sort();
export const categories = Array.from(new Set(commitments.map((item) => item.category))).sort();

export function getCommitmentBySlug(slug: string): Commitment | undefined {
  return commitments.find((item) => item.slug === slug);
}
